- name: Install dependencies
  ansible.builtin.apt:
    name:
      - unzip
      - curl
    update_cache: true

- name: Download and install Consul
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/consul/1.17.0/consul_1.17.0_linux_amd64.zip"
    dest: /usr/local/bin/
    remote_src: true
    mode: '0755'
    creates: /usr/local/bin/consul

- name: Create consul system user
  ansible.builtin.user:
    name: consul
    system: true
    shell: /usr/sbin/nologin
    home: /opt/consul

- name: Create Consul config directory
  ansible.builtin.file:
    path: /etc/consul.d
    state: directory
    mode: '0755'

- name: Create Consul data directory
  ansible.builtin.file:
    path: /opt/consul
    state: directory
    mode: '0755'

- name: Set ownership of Consul data directory (safe)
  ansible.builtin.file:
    path: /opt/consul
    owner: consul
    group: consul
    state: directory
    mode: '0755'

- name: Upload Consul agent config
  ansible.builtin.template:
    src: agent.hcl.j2
    dest: /etc/consul.d/agent.hcl
    mode: '0644'
  notify: Restart Consul
<<<<<<< HEAD
=======

- name: DEBUG — check if template file exists locally
  ansible.builtin.stat:
    path: "{{ role_path }}/templates/consul.service.j2"
  register: consul_template_check

- name: DEBUG — fail if template file not found
  ansible.builtin.fail:
    msg: "TEMPLATE MISSING: {{ role_path }}/templates/consul.service.j2"
  when: not consul_template_check.stat.exists
>>>>>>> 6d361f6 (Add ip-vars in terraform)

- name: Upload Consul systemd service
  ansible.builtin.template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    mode: '0644'
    force: true
  notify: Restart Consul

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Assert that systemd unit file for consul exists
  ansible.builtin.stat:
    path: /etc/systemd/system/consul.service
  register: consul_unit
<<<<<<< HEAD
=======

- name: Fail if consul unit file is missing
  ansible.builtin.fail:
    msg: "Consul systemd unit file is missing!"
  when: not consul_unit.stat.exists
>>>>>>> 6d361f6 (Add ip-vars in terraform)

- name: Start and enable Consul service
  ansible.builtin.systemd:
    name: consul
    state: started
    enabled: true

- name: Register Consul in Consul via HTTP
  delegate_to: "{{ consul_domain }}"
  ansible.builtin.uri:
    url: "http://localhost:8500/v1/agent/service/register"
    method: PUT
    body: "{{ lookup('template', 'consul.json.j2') }}"
    headers:
      Content-Type: "application/json"
    body_format: json