---
- name: Create Netbox directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ netbox_config_dir }}"
    - "{{ netbox_data_dir }}"

- name: Copy Netbox docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ netbox_data_dir }}/docker-compose.yml"
    mode: '0644'

- name: Ensure Docker is installed
  include_tasks: docker.yml
  when: ansible_os_family == "Debian"

- name: Deploy Netbox using Docker Compose
  docker_compose:
    project_src: "{{ netbox_data_dir }}"
    files:
      - docker-compose.yml
    state: present

- name: Wait for Netbox to be ready
  uri:
    url: "http://localhost:8000"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10 