---
# Netbox configuration defaults
netbox_version: "v3.6.2"
netbox_config_dir: "{{ config_dir }}/netbox"
netbox_data_dir: "{{ app_dir }}/netbox"
netbox_secret_key: "{{ lookup('password', '/dev/null length=50 chars=ascii_letters,digits') }}"
netbox_superuser:
  username: admin
  password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
  email: admin@example.com

netbox_ports:
  - "8000:8000" 