- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true

- name: Ensure Traefik config directory
  file:
    path: /opt/traefik
    state: directory

- name: Copy static config
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml

- name: Run Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:v3.0
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/opt/traefik/traefik.yml:/etc/traefik/traefik.yml"