- name: Install dependencies
  ansible.builtin.apt:
    name:
      - unzip
      - curl
      - jq
    update_cache: true

- name: Download Traefik binary
  ansible.builtin.get_url:
    url: "https://github.com/traefik/traefik/releases/download/v2.11.0/traefik_v2.11.0_linux_amd64.tar.gz"
    dest: /tmp/traefik.tar.gz
    mode: '0755'
    force: false

- name: Extract and install Traefik
  ansible.builtin.unarchive:
    src: /tmp/traefik.tar.gz
    dest: /usr/local/bin/
    remote_src: true
    mode: '0755'

- name: Create Traefik config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/traefik
    - /etc/traefik/config

- name: Upload static config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: '0644'
  notify: Restart Traefik

- name: Upload Traefik systemd service
  ansible.builtin.template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    mode: '0644'
  notify: Restart Traefik

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and enable Traefik
  ansible.builtin.systemd:
    name: traefik
    state: started
    enabled: true

- name: Register Traefik in Consul via HTTP
  delegate_to: "{{ consul_domain }}"
  ansible.builtin.uri:
    url: "http://localhost:8500/v1/agent/service/register"
    method: PUT
    body: "{{ lookup('template', 'traefik.json.j2') }}"
    headers:
      Content-Type: "application/json"
    body_format: json
